version: "3.9"

services:
  application:
    build: .
    ports:
      - "8080:8080"
  database:
    image: "postgres:latest"
    hostname: "database"
    ports:
      - "5432:5432"
    volumes:
      - "~/docker/volumes/postgres:/var/lib/postgresql/data"
